name: JFrog Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # For example : v1.0.0, v2.3.4
    branches:
      - cx-master

jobs:
  jfrog-publish:
    name: jfrog-publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/cx-master'
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 20

      - name: set up jfrog cli
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_URL: ${{ secrets.JF_URL }}

      - name: Set CLI Config
        run: jf npm-config --global=true

      - name: Install dependencies
        run: npm ci

      - name: Build & pack
        run: |
          npm run build
          npm pack

      - name: Publish to JFrog
        run: |
          jfrog rt upload *.tgz ${{ secrets.JF_URL }}
