name: JFrog Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # For example : v1.0.0, v2.3.4
    branches:
      - cx-master

env:
  PACKAGE_NAME: cx-json-formatter
  ARTIFACTORY_URL: https://cgx.jfrog.io/artifactory/
  ARTIFACTORY_USERNAME: integrations-actions

jobs:
  jfrog-publish:
    name: jfrog-publish
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/cx-master'
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 20

      - name: set up jfrog cli
        uses: jfrog/setup-jfrog-cli@v4

      - name: Set CLI Config
        run: jf npm-config --global=true

      - name: Install dependencies
        run: npm ci

      - name: Build & pack
        run: |
          npm run build
          npm pack

      - name: Publish to JFrog
        run: |
          jfrog rt upload "${{ env.PACKAGE_NAME }}-*.tgz" ${{ secrets.JF_REPOSITORY_PATH }} --url ${{ secrets.JF_ARTIFACTORY_URL }} --access-token=${{ secrets.ARTIFACTORY_NONUSER_ACCESS_TOKEN }}
